### ISSUE TITLE
Notea won't save

### ISSUE THREAD

**Issue by dom6770** [diamkil/docker-notea#2]
Hey!

I just discovered your wonderful stack, and created a docker-compose file, started it up, and got it running.

```
version: '3.3'
services:
  notea:
    image: diamkil/notea:latest
    hostname: notea
    container_name: Notea
    
    restart: unless-stopped
    
    ports:
      - 7080:3000
      - 7081:9000
    environment:
      - PASSWORD=asdf
      - STORE_USER=asdf
      - STORE_PASSWORD=asdf
    volumes:
      - "/docker/notea:/data"
```

but whenever I type something it resets back.

https://i.imgur.com/fULHV2g.mp4

I attached to the docker container, but nothing shows up in the log.
